
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * principal.java
 *
 * Created on 02/06/2010, 22:04:24
 */
/**
 *
 * @author Juliano
 */
public class principal extends javax.swing.JFrame {

    /** Creates new form principal */
    public principal() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomearquivo = new javax.swing.JTextField();
        busca = new javax.swing.JButton();
        iniciar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        texto = new javax.swing.JTextArea();
        frase = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        texto2 = new javax.swing.JTextArea();
        lblArvore = new javax.swing.JLabel();
        lblGramatica = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtRandom = new javax.swing.JTextArea();
        txbGeraRandom = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnLimpar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("INF05005 - Trabalho Final - Ciro, Guilherme, Juliano");
        setBackground(new java.awt.Color(153, 153, 255));
        setResizable(false);

        nomearquivo.setEditable(false);
        nomearquivo.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                nomearquivoCaretUpdate(evt);
            }
        });
        nomearquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomearquivoActionPerformed(evt);
            }
        });

        busca.setText("Procurar");
        busca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                buscaMouseReleased(evt);
            }
        });
        busca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscaActionPerformed(evt);
            }
        });
        busca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buscaKeyReleased(evt);
            }
        });

        iniciar.setText("Parsear");
        iniciar.setEnabled(false);
        iniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                iniciarMouseReleased(evt);
            }
        });
        iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarActionPerformed(evt);
            }
        });
        iniciar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                iniciarKeyReleased(evt);
            }
        });

        texto.setColumns(20);
        texto.setRows(5);
        texto.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        texto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textoFocusGained(evt);
            }
        });
        jScrollPane1.setViewportView(texto);

        frase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fraseActionPerformed(evt);
            }
        });

        jLabel1.setText("Parsear uma frase:");

        texto2.setColumns(20);
        texto2.setRows(5);
        jScrollPane2.setViewportView(texto2);

        lblArvore.setText("Árvore de Derivação");

        lblGramatica.setText("Gramática na FNC");

        txtRandom.setColumns(20);
        txtRandom.setRows(5);
        jScrollPane3.setViewportView(txtRandom);

        txbGeraRandom.setText("Gera Frase");
        txbGeraRandom.setEnabled(false);
        txbGeraRandom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txbGeraRandomMouseReleased(evt);
            }
        });
        txbGeraRandom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txbGeraRandomActionPerformed(evt);
            }
        });

        jLabel2.setText("INF05005 - Trabalho Final - Ciro, Guilherme, Juliano");

        btnLimpar.setLabel("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        jLabel3.setText("Geração randômica de palavras:");

        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblArvore)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(nomearquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(busca))
                        .addComponent(iniciar)
                        .addComponent(jLabel1)
                        .addComponent(frase, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                        .addComponent(jScrollPane2)
                        .addComponent(lblGramatica)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txbGeraRandom)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpar)
                        .addGap(110, 110, 110)
                        .addComponent(jButton1))
                    .addComponent(jLabel3))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomearquivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(busca)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(frase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iniciar)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblArvore)
                    .addComponent(txbGeraRandom)
                    .addComponent(btnLimpar)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblGramatica)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscaActionPerformed

    private void buscaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_buscaKeyReleased

    private void iniciarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_iniciarKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_iniciarKeyReleased

    private void buscaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscaMouseReleased
        // TODO add your handling code here:
        String caminho = null;
        JFileChooser abrir = new JFileChooser();
        int retorno = abrir.showOpenDialog(null);
        if (retorno == JFileChooser.APPROVE_OPTION) {
            caminho = abrir.getSelectedFile().getAbsolutePath();
            nomearquivo.setText(caminho);

        }
    }//GEN-LAST:event_buscaMouseReleased

    private void iniciarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iniciarMouseReleased
        // TODO add your handling code here:

        chomsky teste = new chomsky();
        ArrayList<String[]> novo = teste.criachomsky(nomearquivo.getText());
        cyk algoritimo = new cyk();
        Palavra gerador = new Palavra();
        Boolean aceitou = false;

        //Limpa as janelas de texto.
        texto.setText(null);
        texto2.setText(null);


        novo = teste.criachomsky(nomearquivo.getText());
        String palavra = frase.getText().replace("  ", " ");
        palavra = palavra.replace(",", " ,");
        palavra = palavra.replace(".", " .");
        palavra = palavra.replace("!", " !");
        palavra = palavra.replace("?", " ?");
        String[] terminais = palavra.split(" ");
        Object[][] nodos = new Object[terminais.length + 1][terminais.length + 1];

        ArrayList<String[]> fim = algoritimo.cyk(terminais, terminais.length, novo, nodos);
        if (fim == null) {
            aceitou = false;
        } else {
            aceitou = true;
        }

        if (aceitou) {
            int i;
            int j;
            int linha = 0;
            int linhas = 1;
            String word = null;
            texto.setText(null);
            ArrayList<String> inverte = new ArrayList<String>();
            ;
            inverte.clear();

//        for (i=0;i < linhas; i++){
//                texto.append("\n");
//        }

            String[] ttt = new String[3];
            for (i = fim.size() - 1; i >= 0; i--) {
                ttt = fim.get(i);
                inverte.add("|");
                if (ttt.length == 0) {
                    inverte.add(" | ß ");
                } else {
                    if ((ttt[0] == " ") | (ttt[0] == null)) {
                        inverte.add(" | ß ");
                    } else {
                        inverte.add(" | " + ttt[0]);
                    }
                }


                for (j = 1; j < ttt.length - 1; j++) {
                    inverte.add(", " + ttt[j]);
                }

                //

                linha++;
                if (linha == linhas) {
                    for (j = inverte.size() - 1; j >= 0; j--) {
                        texto.append(inverte.get(j));
                    }
                    texto.append("\n");
                    inverte.clear();
                    linha = 0;
                    linhas++;
                }
            }

            for (i = 0; i < terminais.length; i++) {
                texto.append(" | ");
                texto.append(terminais[i]);
                texto.append(" | ");

            }


        } else {
            texto.append("Uma das palavras não pertence a gramática!");
        }
        String[] ttt = new String[3];
        int i = 0;
        // texto.setText(null);

        String prob = null;
        for (i = 0; i < novo.size(); i++) {
            ttt = novo.get(i);
            prob = ";" + ttt[2];
            texto2.append(ttt[0] + " > " + ttt[1] + prob + "\n");

        }
    }//GEN-LAST:event_iniciarMouseReleased

    private void textoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_textoFocusGained

    private void fraseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fraseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fraseActionPerformed

    private void iniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iniciarActionPerformed

    /*
     * Código para gerar texto randômico.
     * Autor: Guilherme Severo.
     */
    private void txbGeraRandomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txbGeraRandomActionPerformed
    }//GEN-LAST:event_txbGeraRandomActionPerformed

    private void txbGeraRandomMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txbGeraRandomMouseReleased
        // TODO add your handling code here:
        Palavra gerador = new Palavra();
        chomsky teste = new chomsky();
        ArrayList<String[]> novo = teste.criachomsky(nomearquivo.getText());
        String palavra = new String();

        palavra = gerador.geraRandomica(novo, novo.get(0)[0], novo.get(0)[0]);

        palavra = palavra.replace(" ", "");
        palavra = palavra.replace("[", "");
        palavra = palavra.replace("]", " ");
        palavra = palavra.replace(" , ", ", ");
        palavra = palavra.replace(" . ", ". ");
        palavra = palavra.replace(" ! ", "! ");
        palavra = palavra.replace(" ? ", "? ");

        txtRandom.append(palavra.trim() + " \n");
    }//GEN-LAST:event_txbGeraRandomMouseReleased

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // Limpa a tela de texto
        txtRandom.setText(null);
    }//GEN-LAST:event_btnLimparActionPerformed

    private void nomearquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomearquivoActionPerformed
    }//GEN-LAST:event_nomearquivoActionPerformed

    private void nomearquivoCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_nomearquivoCaretUpdate
        txbGeraRandom.setEnabled(true);
        btnLimpar.setEnabled(true);
        iniciar.setEnabled(true);
    }//GEN-LAST:event_nomearquivoCaretUpdate

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String caminhoArquivo = JOptionPane.showInputDialog(null, "Digite o nome do arquivo");
        caminhoArquivo = caminhoArquivo + ".txt";
        try {
            FileWriter writer = new FileWriter(new File(caminhoArquivo));
            PrintWriter saida = new PrintWriter(writer);
            saida.println(txtRandom.getText());
            writer.close();
            saida.close();

        } catch (IOException ex) {
            //Logger.getLogger(TestesDiversos.class.getName()).log(Level.SEVERE, null, ex);
        }



    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new principal().setVisible(true);
            }
        });

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton busca;
    private javax.swing.JTextField frase;
    private javax.swing.JButton iniciar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblArvore;
    private javax.swing.JLabel lblGramatica;
    private javax.swing.JTextField nomearquivo;
    private javax.swing.JTextArea texto;
    private javax.swing.JTextArea texto2;
    private javax.swing.JButton txbGeraRandom;
    private javax.swing.JTextArea txtRandom;
    // End of variables declaration//GEN-END:variables
}
